### ISSUE TITLE
Move Roles to Church Level from Application Level

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AccessApi#29]
Currently roles are associated with a specific application within a church (Chums, StreamingLive, etc).  This no longer makes sense since we're often granting access to the core apis that are shared between applications.  Let's remove the appName column from the roles table and update the AccountsApp interface to list these roles directly under the church.

As part of this, the registration code for each application will need to be updated.  Instead of Chums creating a new "Administrators" group and associating it with the Chums application.  It'll create a "Chums Administrators" group and associate it to the church.

**Comment by pranavmalvawala** [comment]
Init DB changes for this issue https://github.com/LiveChurchSolutions/AccessApi/commit/7bacd33d2eb75541ed614185c3fb1997d5efafca
