### ISSUE TITLE
Add /churches/select route

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AccessApi#39]
Add a route for someone to manually specify a church they want to select.  This route will receive a jwt so the user will be authorized.  It should return the same church object that /users/login returns and array of with api permissions and jwts, but for this single church.  If the user is granted any roles for that church directly, it'll need to include those, otherwise it'll need to include the "Everyone" list of permissions.

**Comment by pranavmalvawala** [comment]
I think the route should be `GET /churches/select/:churchId` cause I'm not sure that the jwt passed in the API headers will always have the churchId that we'd wanna fetch.

**Comment by jzongker** [comment]
Yes, definitely need to pass the churchId they wish to select.  The jwt is just to authenticate who the user is, not the desired church.  I was originally thinking it would be a POST to /churches/select and pass in the churchId, but it could be a GET to /church/select/:churchId instead.
