### ISSUE TITLE
Create a prisma demo 

### ISSUE THREAD

**Issue by pranavmalvawala** [LiveChurchSolutions/AccessApi#49]

**Comment by jzongker** [comment]
FYI that ReportingApi is currently using https://www.prisma.io/ for the graphql code.  May want to look into that instead.  Not sure I'm a fan of using an ORM across the board vs direct mysql queries...

**Comment by pranavmalvawala** [comment]
I Totally get it, why spend time getting to know an ORM when we are capable of writing raw queries and btw you are pretty amazing at it, ORM has its benefits though. 

I wouldn't change much in the code though cause we've built whole system on top of it. I was actually gonna implement this thing for one small section and see if it simplifies things and then propose the change if we can change everything in 2-3 days.
