### ISSUE TITLE
Remove app activations and associated tables

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AccessApi#76]
The concept of app activations is going away.  Remove the applications and churchApplications tables along with all associated code.

**Comment by pranavmalvawala** [comment]
`churchapps` table to be precise.

**Comment by pranavmalvawala** [comment]
There are 2 more tables that could be possible deleted - `applicationapis` and `permissions`

**Comment by pranavmalvawala** [comment]
Make sure to also remove all interfaces from backend and frontend

**Comment by pranavmalvawala** [comment]
Looks like `apis` table is also not used anywhere. Remove it.
