### ISSUE TITLE
Allow non-latin characters in church search

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AccessApi#98]
The /churches/search route is currently a GET and API gateway blocks non-latin characters in the query string.  Add a POST version of this method (but don't remove GET yet) and update the church search in appBase to use it.

See the recent changes to the person search for an example of how to implement.
https://github.com/LiveChurchSolutions/MembershipApi/commit/5eef4bfb409caac18b657ebb6407b9b643e24db6
https://github.com/LiveChurchSolutions/AppBase/commit/62cdc287f75ef1d0398df80d661fa03f32376c3c

**Comment by PhotoPaul** [comment]
After looking further into it, I figured out that it doesn't really "block" them, but that further decoding is needed.
So this: `req.query.name.toString()`
needs to become this `decodeURIComponent(JSON.parse('"' + req.query.name.toString().replace(/%u/g, '\\u') + '"'))`

Can you please confirm this is an acceptable solution (or not) over switching everything to POST?
